version: '3.5'

services:
  db: 
    image: postgres
    hostname: db
    network_mode: host
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: schedules
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'

  redis:
    container_name: redis-dev
    network_mode: host
    image: redis
    restart: always
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    environment:
      - REDIS_HOST_PASSWORD=pass
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1GB'
